<?php
/**
 * Created by PhpStorm.
 * User: IronHide
 * Date: 12/19/2016
 * Time: 1:08 PM
 */

namespace AppBundle\Utils;


class AppConstants
{

    const ROWS_PER_PAGE = 50;

    const DEFAULT_SMS_NOTIFICATION_MESSAGE = "Federal Character Commission Has Sent You An Email. Please Check Your Email Inbox or Spam Folder And Respond Accordingly.";
    const DEFAULT_SMS_NOTIFICATION_SUFFIX = "Has Sent You An Email. Please Check Your Email Inbox or Spam Folder And Respond Accordingly.";
    const FCC_SMS_SENDER = "FED CHAR CO";
    const FCC_EMAIL_SENDER_NAME = "Federal Character Commission Portal";
    const FCC_EMAIL_SENDER_EMAIL = "saleahmadu@gmail.com";

    const FCC = 'FCC';
    const MDA = 'MDA';

    const DEV_UPLOAD_BASE_DIR = "C:" . DIRECTORY_SEPARATOR . "FCC_DATA_PROCESSING_PORTAL" . DIRECTORY_SEPARATOR;
    const DEV_PUBLIC_UPLOAD_BASE_DIR = "C:" . DIRECTORY_SEPARATOR . "Apache24" . DIRECTORY_SEPARATOR . "htdocs" . DIRECTORY_SEPARATOR . "fcc_portal_docs" . DIRECTORY_SEPARATOR;

    const PROD_UPLOAD_BASE_DIR = DIRECTORY_SEPARATOR . "home" . DIRECTORY_SEPARATOR . "federalc" . DIRECTORY_SEPARATOR . "FCC_PORTAL" . DIRECTORY_SEPARATOR;
    const PROD_PUBLIC_UPLOAD_BASE_DIR = DIRECTORY_SEPARATOR . "home" . DIRECTORY_SEPARATOR . "federalc" . DIRECTORY_SEPARATOR . "public_html" . DIRECTORY_SEPARATOR . "fcc_portal_docs" . DIRECTORY_SEPARATOR;

    const DEV_NOMINAL_ROLL_UPLOAD_DIR = self::DEV_UPLOAD_BASE_DIR . "NOMINAL_ROLL" . DIRECTORY_SEPARATOR;
    const PROD_NOMINAL_ROLL_UPLOAD_DIR = self::PROD_UPLOAD_BASE_DIR . "NOMINAL_ROLL" . DIRECTORY_SEPARATOR;

    const DEV_DOWNLOAD_MANAGER_UPLOAD_DIR = self::DEV_UPLOAD_BASE_DIR . "downloads" . DIRECTORY_SEPARATOR;
    const PROD_DOWNLOAD_MANAGER_UPLOAD_DIR = self::PROD_UPLOAD_BASE_DIR . "downloads" . DIRECTORY_SEPARATOR;

    const DEV_VACANCY_UPLOAD_DIR = self::DEV_PUBLIC_UPLOAD_BASE_DIR . "vacancy" . DIRECTORY_SEPARATOR;
    const PROD_VACANCY_UPLOAD_DIR = self::PROD_PUBLIC_UPLOAD_BASE_DIR . "vacancy" . DIRECTORY_SEPARATOR;

    const DEV_PROFILE_PHOTO_UPLOAD_DIR = self::DEV_PUBLIC_UPLOAD_BASE_DIR . "user_profile" . DIRECTORY_SEPARATOR;
    const PROD_PROFILE_PHOTO_UPLOAD_DIR = self::PROD_PUBLIC_UPLOAD_BASE_DIR . "user_profile" . DIRECTORY_SEPARATOR;

    const DEV_UPLOAD_TRASH_DIR = self::DEV_UPLOAD_BASE_DIR . "TRASH" . DIRECTORY_SEPARATOR;
    const PROD_UPLOAD_TRASH_DIR = self::PROD_UPLOAD_BASE_DIR . "trash" . DIRECTORY_SEPARATOR;

    const DEV_PUBLIC_UPLOAD_TRASH_DIR = self::DEV_PUBLIC_UPLOAD_BASE_DIR . "trash" . DIRECTORY_SEPARATOR;
    const PROD_PUBLIC_UPLOAD_TRASH_DIR = self::PROD_PUBLIC_UPLOAD_BASE_DIR . "trash" . DIRECTORY_SEPARATOR;

    const DEV_PUBLIC_VACANCY_UPLOAD_URL = 'http://localhost/fcc_portal_docs/vacancy/';
    const PROD_PUBLIC_VACANCY_UPLOAD_URL = 'http://federalcharacter.gov.ng/fcc_portal_docs/vacancy/';

    const DEV_PUBLIC_UPLOAD_TRASH_URL = 'http://localhost/fcc_portal_docs/trash/';
    const PROD_PUBLIC_UPLOAD_TRASH_URL = 'http://federalcharacter.gov.ng/fcc_portal_docs/trash/';

    const DEV_PUBLIC_PROFILE_URL = 'http://localhost/fcc_portal_docs/user_profile/';
    const PROD_PUBLIC_PROFILE_URL = 'http://federalcharacter.gov.ng/fcc_portal_docs/user_profile/';

    const TO_MDA_DESK_OFFICERS = "TO_MDA_DESK_OFFICERS";

    //SYSTEM RESERVED ROLES
    const ROLE_USER = "ROLE_USER";
    const ROLE_SUPER_ADMIN = 4000;
    const ROLE_MIS_HEAD = 5000;


    const ROLE_MDA_ADMIN = 5002;

    const ROLE_FCC_DESK_OFFICER_FEDERAL = 5001;
    const ROLE_FCC_COMMISSIONER = 5003;
    const ROLE_FCC_COMMITTEE_SECRETARY = 5004;
    const ROLE_FCC_COMMITTEE_CHAIRMAN = 5008;

    const FCC_USER = "FCC_USER";
    const MDA_USER = "MDA_USER";

    const DUPLICATE_USERNAME = 'DUPLICATE_USERNAME';
    const DUPLICATE_NAME = 'DUPLICATE_NAME';
    const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';
    const DUPLICATE_PRIMARY_PHONE = 'DUPLICATE_PRIMARY_PHONE';
    const DUPLICATE_SECONDARY_PHONE = 'DUPLICATE_SECONDARY_PHONE';

    const DUPLICATE = 'DUPLICATE';
    const DUPLICATE_CODE = 'DUPLICATE_CODE';
    const DUPLICATE_YEAR = 'DUPLICATE_YEAR';
    const DUPLICATE_DESC = 'DUPLICATE_DESC';
    const DUPLICATE_GUID = 'DUPLICATE_GUID';
    const DUPLICATE_FCC_DESK_OFFICER_COMMITTEE = 'DUPLICATE_FCC_DESK_OFFICER_COMMITTEE';

    const CANNOT_UPDATE = 'CANNOT_UPDATE';

    const ACTIVE = 'ACTIVE';
    const INACTIVE = 'INACTIVE';
    const EXIT = 'EXIT';

    const CANCEL = 'CANCEL';
    const CANCELLED = 'CANCELLED';

    const NEW = 'NEW';
    const EDIT = 'EDIT';
    const DELETE = 'DELETE';

    const REQUEST = 'REQUEST';

    const OPEN_NOTIFICATION = 'OPEN_NOTIFICATION';

    const CAREER_CIVIL_SERVANT = 'CAREER_CIVIL_SERVANT';
    const POLITICAL_OFFICE_HOLDER = 'POLITICAL_OFFICE_HOLDER';

    //cache item keys
    const KEY_CACHED_NATIONALITY_CODES = 'app.cached_nationality_codes';
    const KEY_CACHED_GEO_POLITICAL_ZONES = 'app.cached_geo_political_zones';
    const KEY_CACHED_NIGERIAN_STATES = 'app.cached_nigerian_states';
    const KEY_CACHED_STATE_LGAS = 'app.cached_state_lgas';
    const KEY_CACHED_GENDER = 'app.cached_gender';
    const KEY_CACHED_SUBMISSION_STATUS = 'app.cached_submission_status';
    const KEY_CACHED_FCC_ROLES = 'app.cached_fcc_roles';
    const KEY_CACHED_MDA_ROLES = 'app.cached_mda_roles';

    const KEY_CACHED_ROLES = 'app.cached_roles';
    const KEY_CACHED_ROLE_CATEGORIES = 'app.cached_role_categories';
    const KEY_CACHED_COMMITTEES = 'app.cached_committees';
    const KEY_CACHED_DEPARTMENTS = 'app.cached_departments';
    const KEY_CACHED_FCC_USERS = 'app.cached_fcc_users';
    const KEY_CACHED_ORGANIZATIONS = 'app.cached_organizations';
    const KEY_CACHED_CLIENT_ORGANIZATION = 'app.cached_client_organization';
    const KEY_CACHED_SUBMISSION_YEARS = 'app.cached_submission_years';
    const KEY_CACHED_SYSTEM_PRIVILEGES = 'app.cached_system_privileges';
    const KEY_CACHED_SYSTEM_ROLE_PRIVILEGES = 'app.cached_system_role_privileges';

    const KEY_CACHED_STATIC_CONTENT = 'app.cached_static_content';
    const KEY_CACHED_POLITICAL_OFFICE_GRADE_LEVELS = 'app.cached_political_office_grade_levels';
    const KEY_CACHED_CAREER_CIVIL_SERVANT_GRADE_LEVELS = 'app.cached_career_civil_servant_grade_levels';

    const KEY_CACHED_MARITAL_STATUS = 'app.cached_marital_status';
    const KEY_CACHED_SUBMISSION_TYPES = 'app.cached_submission_types';
    const KEY_CACHED_APPROVAL_STATUS = 'app.cached_approval_status';
    const KEY_CACHED_ORGANIZATION_CATEGORY_TYPES = 'app.cached_organization_category_types';
    const KEY_CACHED_CBI_REPORT_GL_CATEGORIES = 'app.cached_cbi_report_gl_categories';
    const KEY_CACHED_DOWNLOAD_CATEGORIES = 'app.cached_download_categories';

    //user profile types
    const FCC_USER_PROFILE = 'FCC_USER';
    const MDA_USER_PROFILE = 'MDA_USER';

    const ALERT_SUCCESS = 'success';
    const ALERT_INFO = 'info';
    const ALERT_WARNING = 'warning';
    const ALERT_DANGER = 'danger';

    const CBI_REQUEST_TYPE_NORMAL = 'NORMAL';
    const CBI_REQUEST_TYPE_RECRUITMENT = 'RECRUITMENT';

    const Y = 'Y';
    const N = 'N';

    const YES = 'YES';
    const NO = 'NO';

    const FEDERAL = "FEDERAL";
    const STATE = "STATE";
    const LOCAL_GOVERNMENT = "LOCAL_GOVERNMENT";

    const FEDERAL_MINISTRY_ESTABLISHMENT = "FEDERAL_MINISTRY";
    const FEDERAL_PARASTATAL_ESTABLISHMENT = "FEDERAL_PARASTATAL";
    const STATE_MINISTRY_ESTABLISHMENT = "STATE_MINISTRY";
    const STATE_PARASTATAL_ESTABLISHMENT = "STATE_PARASTATAL";

    const RECIPIENT_EMAILS_ADDRESSES = 'recipient_email_addresses';
    const RECIPIENT_PHONE_NUMBERS = 'recipient_phone_numbers';
    const FEDERAL_MDA = 'FEDERAL_MDA';


    const ACADEMIC_ESTABLISHMENT = 1;

    const PENDING = 'PENDING';
    const APPROVED = 'APPROVED';
    const DECLINED = 'DECLINED';
    const FAILED = 'FAILED';
    const PASSED = 'PASSED';
    const STARTED = 'STARTED';
    const COMPLETED = 'COMPLETED';
    const CONFIRMED = 'CONFIRMED';
    const RECOMMENDED = 'RECOMMENDED';
    const FATAL_ERROR = 'FATAL_ERROR';
    const INCOMPLETE = 'INCOMPLETE';

    const MAIN_SUBMISSION = 'MAIN_SUBMISSION';
    const QUARTERLY_RETURN = 'QUARTERLY_RETURN';

    const FIRST_SUBMISSION = "FIRST_SUBMISSION";
    const ADDITIONAL_SUBMISSION = "ADDITIONAL_SUBMISSION";
    const FIRST_NON_SEQUENTIAL_SUBMISSION = "FIRST_NON_SEQUENTIAL_SUBMISSION";

    const LONG_LIST = "LONG_LIST";
    const SHORT_LIST = "SHORT_LIST";
    const COC_CANDIDATE_LIST = "COC_CANDIDATE_LIST";
    const COC_CANDIDATE_APPOINTMENT_LIST = "COC_CANDIDATE_APPOINTMENT_LIST";

    const INVALID_EMPLOYEE_STATUS = "INVALID_EMPLOYEE_STATUS";
    const INVALID_EMPLOYEE_NUMBER = "INVALID_EMPLOYEE_NUMBER";
    const INVALID_NAME = "INVALID_NAME";
    const INVALID_SURNAME = "INVALID_SURNAME";
    const INVALID_FIRST_NAME = "INVALID_FIRST_NAME";
    const INVALID_OTHER_NAME = "INVALID_OTHER_NAME";
    const INVALID_ADDRESS = "INVALID_ADDRESS";
    const INVALID_CENTER = "INVALID_CENTER";
    const INVALID_PHONE = "INVALID_PHONE";
    const INVALID_EMAIL = "INVALID_EMAIL";
    const INVALID_POST_APPLIED = "INVALID_POST_APPLIED";
    const INVALID_UNIVERSITY = "INVALID_UNIVERSITY";
    const INVALID_COURSE = "INVALID_COURSE";
    const INVALID_DEGREE = "INVALID_DEGREE";
    const INVALID_APPOINTMENT_STATUS = "INVALID_APPOINTMENT_STATUS";
    const INVALID_NATIONALITY_CODE = "INVALID_NATIONALITY_CODE";
    const INVALID_STATE_OF_ORIGIN = "INVALID_STATE_OF_ORIGIN";
    const INVALID_DATE_OF_BIRTH = "INVALID_DATE_OF_BIRTH";
    const INVALID_DATE_OF_EMPLOYMENT = "INVALID_DATE_OF_EMPLOYMENT";
    const INVALID_DATE_OF_PRESENT_APPOINTMENT = "INVALID_DATE_OF_PRESENT_APPOINTMENT";
    const INVALID_GRADE_LEVEL = "INVALID_GRADE_LEVEL";
    const INVALID_DESIGNATION = "INVALID_DESIGNATION";
    const INVALID_STATE_OF_LOCATION = "INVALID_STATE_OF_LOCATION";
    const INVALID_GENDER = "INVALID_GENDER";
    const INVALID_MARITAL_STATUS = "INVALID_MARITAL_STATUS";
    const INVALID_LGA = "INVALID_LGA";
    const INVALID_GEO_POLITICAL_ZONE = "INVALID_GEO_POLITICAL_ZONE";
    const INVALID_PHYSICALLY_CHALLENGED_STATUS = "INVALID_PHYSICALLY_CHALLENGED_STATUS";
    const INVALID_QUARTERLY_RETURN_EMPLOYMENT_STATUS = "INVALID_QUARTERLY_RETURN_EMPLOYMENT_STATUS";

    const INVALID_LGA_OF_ORIGIN = "INVALID_LGA_OF_ORIGIN";
    const INVALID_SENATORIAL_DISTRICT = "INVALID_SENATORIAL_DISTRICT";
    const INVALID_LGA_OF_DEPLOYMENT = "INVALID_LGA_OF_DEPLOYMENT";

    const INVALID_NOT_IN_LONG_LIST = "INVALID_NOT_IN_LONG_LIST";
    const INVALID_DUPLICATE_RECORD = "INVALID_DUPLICATE_RECORD";
    const INVALID_DUPLICATE_PREVIOUS_RECORD = "INVALID_DUPLICATE_PREVIOUS_RECORD";

    const STATIC_CONTENT_FEDERAL_LEVEL_NOMINAL_ROLE_SUBMISSION_INSTRUCTIONS = 'FEDERAL_LEVEL_NOMINAL_ROLE_SUBMISSION_INSTRUCTIONS';
    const STATIC_CONTENT_LOGIN_PAGE_APPLICATION_NAME = 'LOGIN_PAGE_APPLICATION_NAME';
    const STATIC_CONTENT_NOMINAL_ROLE_DEMAND_NOTICE_MESSAGE = 'NOMINAL_ROLE_DEMAND_NOTICE_MESSAGE';
    const STATIC_CONTENT_NOMINAL_ROLE_DEMAND_NOTICE_REMINDER_MESSAGE = 'NOMINAL_ROLE_DEMAND_NOTICE_REMINDER_MESSAGE';
    const STATIC_CONTENT_STATE_LEVEL_NOMINAL_ROLE_SUBMISSION_INSTRUCTIONS = 'STATE_LEVEL_NOMINAL_ROLE_SUBMISSION_INSTRUCTIONS';

    const GRADE_LEVEL_CHIEF_EXECUTIVES = '90';

    //ADMIN PRIVILEGES
    const PRIV_CMS_MANAGE = "CMS_MANAGE";
    const PRIV_COMMITTEE_LIST = "COMMITTEE_LIST";
    const PRIV_COMMITTEE_MODIFY = "COMMITTEE_MODIFY";
    const PRIV_FCC_USER_LIST = "FCC_USER_LIST";
    const PRIV_FCC_USER_MODIFY = "FCC_USER_MODIFY";
    const PRIV_FED_MDA_LIST = "FED_MDA_LIST";
    const PRIV_FED_MDA_MODIFY = "FED_MDA_MODIFY";
    const PRIV_MDA_USER_LIST = "MDA_USER_LIST";
    const PRIV_MDA_USER_MODIFY = "MDA_USER_MODIFY";
    const PRIV_ROLE_MANAGE = "ROLE_MANAGE";
    const PRIV_STATE_MDA_LIST = "STATE_MDA_LIST";
    const PRIV_STATE_MDA_MODIFY = "STATE_MDA_MODIFY";

    //FCC PRIVILEGES
    const PRIV_ASSIGNED_MDA_LIST = "ASSIGNED_MDA_LIST";
    const PRIV_COMMITTEE_MDA_LIST = "COMMITTEE_MDA_LIST";
    const PRIV_CONFIRM_FED_MDA_NOMINAL_ROLL_UPLOAD = "CONFIRM_FED_MDA_NOMINAL_ROLL_UPLOAD";
    const PRIV_CONFIRM_STATE_MDA_NOMINAL_ROLL_UPLOAD = "CONFIRM_STATE_MDA_NOMINAL_ROLL_UPLOAD";

    //FED MDA PRIVILEGES
    const PRIV_FED_MDA_UPLOAD_NOMINAL_ROLL = "FED_MDA_UPLOAD_NOMINAL_ROLL";
    const PRIV_FED_MDA_UPLOAD_VACANCY = "FED_MDA_UPLOAD_VACANCY";

    //FEDERAL REPORTS PRIVILEGES
    const PRIV_FED_MDA_CAREER_CHARACTER_BALANCING_INDEX = "FED_MDA_CAREER_CHARACTER_BALANCING_INDEX";
    const PRIV_FED_MDA_CAREER_POST_DIST = "FED_MDA_CAREER_POST_DIST";
    const PRIV_FED_MDA_NOMINAL_ROLL_QUERY = "FED_MDA_NOMINAL_ROLL_QUERY";

    //OTHER REPORTS PRIVILEGES
    const PRIV_FED_CONSOLIDATED_CAREER_POST_DIST = "FED_CONSOLIDATED_CAREER_POST_DIST";
    const PRIV_FED_LEVEL_COMPARATIVE_DATA_ON_STAFF_DIST = "FED_LEVEL_COMPARATIVE_DATA_ON_STAFF_DIST";
    const PRIV_FED_LEVEL_LIST_OF_CHIEF_EXECUTIVES = "FED_LEVEL_LIST_OF_CHIEF_EXECUTIVES";
    const PRIV_FED_POLOH_BY_POST_AND_YEAR_DIST = "FED_POLOH_BY_POST_AND_YEAR_DIST";
    const PRIV_FED_POLOH_POST_DIST = "FED_POLOH_POST_DIST";

    //REPORT MDA LIMIT PRIVILEGES
    const PRIV_ALL_MDA_REPORT_SELECTION_LIMIT = "ALL_MDA_REPORT_SELECTION_LIMIT";
    const PRIV_ASSIGNED_MDA_REPORT_SELECTION_LIMIT = "ASSIGNED_MDA_REPORT_SELECTION_LIMIT";
    const PRIV_COMMITTEE_MDA_REPORT_SELECTION_LIMIT = "COMMITTEE_MDA_REPORT_SELECTION_LIMIT";
    const PRIV_USER_MDA_REPORT_SELECTION_LIMIT = "USER_MDA_REPORT_SELECTION_LIMIT";

    //STATE MDA PRIVILEGES
    const PRIV_STATE_MDA_UPLOAD_NOMINAL_ROLL = "STATE_MDA_UPLOAD_NOMINAL_ROLL";
    const PRIV_STATE_MDA_UPLOAD_VACANCY = "STATE_MDA_UPLOAD_VACANCY";

}
